#%RAML 1.0 DataType
displayName: Meeting
description: Meeting type
#additionalProperties: false
type: object
properties:
  Title:
    type: string
  Duration:
    type: integer
  Comments:
    type: string
  MeetingType:
    type: string