#%RAML 1.0 DataType
displayName: user
description: User type
#additionalProperties: false
type: object
properties:
  userName:
    type: string
  email:
    type: string
  firstName:
    type: string
  lastName:
    type: string
  sapId:
    type: integer