#%RAML 1.0 NamedExample
api: "File Transfer Service"
uri: "/sftp"
timestamp: "2018-12-31T23:59:59.0Z"
type: "INFORMATION"
summary: "The SFTP operation has been completed successfully"
additionalInformation:
  type: "Text"
  details: "The following files have been transferred - mule-1.log, mule-2.log"  