#%RAML 1.0 Library
usage:
types:
  CredentialsPassphraseType:
    type: !include sftp-credentials-passphrase-type.raml
    example:
      passphrase: "e772msff923nml2mk34b63kbqv43jh14h141"
  CredentialsSSHPrivateKeyType:
    type: !include sftp-credentials-sshprivatekey-type.raml
    example:
      sshPrivateKey: "asjhdnoqhdouhou2h3b2b343kb4h3v5jhv12h3vbh21v312jv3jg21c4g314"
