#%RAML 1.0 DataType
type: object
additionalProperties: false
properties:
  passphrase:
    description: The passphrase used to access the SSH Key for the user account to authenticate with the SFTP Server by the File Transfer Service. This is optional and will only be required when the SSH Key is additionally protected by a passphrase and resides as part of the Mule File Transfer Runtime
    type: string
