#%RAML 1.0 NamedExample
id: 24
physicalFileName: AABBCC.pdf
title: Meeting Minutes
uploadedUtcDateTime: 2020-07-01 09:45:11.467
documentTypeId: 11
documentTypeName: Meeting Minutes
physicalRoot: \\Gbrbmccrs00172\btdshr01\Board_Tracking_Dev