#%RAML 1.0 NamedExample
-
  meetingid: 1
  meetingType: 7
  calendarEntryId: 9
  title: Board Meeting
  duration: 90
  comments: a quick brown fox jumped
  date: 2020-01-05 00:00:00.000
  agendaItemTitle: agenda item 1 
  agendaItemDuration: 5
  orderIndex: 1
  presenters: Lilly and Rick
-
  meetingid: 1
  meetingType: 7
  calendarEntryId: 9
  title: Board Meeting
  duration: 90
  comments: a quick brown fox jumped
  date: 2020-01-05 00:00:00.000
  agendaItemTitle: agenda item 2 
  agendaItemDuration: 10
  orderIndex: 2
  presenters: Lilly