#%RAML 1.0 NamedExample
- 
  userName: "user1"
  email: "user1@bentley.com"
  firstName: "User"
  lastName: "One"
  sapId: 123456
-
  userName: "user2"
  email: "user2@bentley.com"
  firstName: "User"
  lastName: "Two"
  sapId: 123457