#%RAML 1.0 NamedExample
api: "Some API"
uri: "/api"
timestamp: "2000-01-01T00:00:00.0Z"
code: <<apiShortName>>_<<apiParentResourceName>><<apiResourceName>><<apiMethodName>>_003
type: "ERROR"
summary: "Not Found"
additionalInformation:
  type: "Text"
  details: "The requested resource in the request cannot be found"