#%RAML 1.0 NamedExample
example1:
  api: "Some API"
  uri: "/api"
  timestamp: "2000-01-01T00:00:00.0Z"
  code: "002"
  type: "WARNING"
  summary: "A validation error occured"
  additionalInformation:
    type: "Text"
    details: "The customer information is missing mandatory fields"
example2:
  !include common-response-example-info.raml