#%RAML 1.0 NamedExample
"api": "Another API"
"uri": "/another-resource"
"timestamp": "2000-01-01T00:00:00.0Z"
"type": "INFORMATION"
"summary": "The request to process the payment was submitted for further processing"