#%RAML 1.0 NamedExample
common-response-example-success:
  "api": "Same API"
  "uri": "/different-resource"
  "timestamp": "2000-01-01T00:00:00.0Z"
  "code": "1234567"
  "type": "SUCCESSFUL"
  "summary": "The transaction record was posted successfully"